version: "3.9"

services:

  devcontainer:
    build:
      context: .
      target: dev
      {%- if private_package_repository_name %}
      secrets:
        - poetry-auth
      {%- endif %}
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-{{ python_version }}}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    {%- if not private_package_repository_name %}
    environment:
      - POETRY_PYPI_TOKEN_PYPI
    {%- else %}
    secrets:
      - poetry-auth
    {%- endif %}
    volumes:
      - ..:/workspaces
      - command-history-volume:/home/user/.history/

  dev:
    extends: devcontainer
    stdin_open: true
    tty: true
    entrypoint: []
    command:
      [
        "sh",
        "-c",
        "sudo chown user $$SSH_AUTH_SOCK && cp --update /opt/build/poetry/poetry.lock /workspaces/{{ package_name | kebab_case }}/ && mkdir -p /workspaces/{{ package_name | kebab_case }}/.git/hooks/ && cp --update /opt/build/git/* /workspaces/{{ package_name | kebab_case }}/.git/hooks/ && zsh"
      ]
    environment:
      {%- if not private_package_repository_name %}
      - POETRY_PYPI_TOKEN_PYPI
      {%- endif %}
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    {%- if with_fastapi_api or with_streamlit_app %}
    ports:
      - "8000"
    {%- endif %}
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh/known_hosts:/home/user/.ssh/known_hosts
      - ${SSH_AGENT_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/run/host-services/ssh-auth.sock
    profiles:
      - dev
  {%- if with_fastapi_api or with_streamlit_app or with_typer_cli %}

  app:
    build:
      context: .
      target: app
      {%- if private_package_repository_name %}
      secrets:
        - poetry-auth
      {%- endif %}
    tty: true
    {%- if with_fastapi_api or with_streamlit_app %}
    ports:
      - "8000:8000"
    {%- endif %}
    profiles:
      - app
  {%- endif %}
{%- if private_package_repository_name %}

secrets:
  poetry-auth:
    file: "${POETRY_AUTH_TOML_PATH:-~/Library/Application Support/pypoetry/auth.toml}"
{%- endif %}

volumes:
  command-history-volume: