name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "{{ python_version }}"

      - name: Install Poetry
        run: pip install --no-input poetry

      - name: Publish package
        run: |
          {%- if private_package_repository_name %}
          poetry config repositories.private "{{ private_package_repository_url | replace(from="simple/", to="") | replace(from="simple", to="") }}"
          poetry config http-basic.private "{% raw %}${{{% endraw %} secrets.POETRY_HTTP_BASIC_{{ private_package_repository_name|slugify(separator="_")|upper }}_USERNAME }}" "{% raw %}${{{% endraw %} secrets.POETRY_HTTP_BASIC_{{ private_package_repository_name|slugify(separator="_")|upper }}_PASSWORD }}"
          poetry publish --build --repository private
          {%- else %}
          poetry config pypi-token.pypi "{% raw %}${{ secrets.POETRY_PYPI_TOKEN_PYPI }}{% endraw %}"
          poetry publish --build
          {%- endif %}